/**
 * lky 2018-11-15
 * 请求服务对应参数
 * 规则：
 * 1、以 REQ_开头
 * 2、webservice请求以REQ_WEB_SER_开头
 */


// var REQ_WEB_SER_CXGDS = 'QueryAgentList';//首页查询工单接口
// var REQ_WEB_SER_CXKGGZD = 'QueryKfsqgzd';//查询客服诉求工作单
// var REQ_WEB_SER_CXTQYHSL = 'QueryAreaUserCount';//台区用户数量查询
// var REQ_WEB_SER_FSTQDX = 'SendAreSMS';//发送台区短信
// var REQ_WEB_SER_CXWGTDSJ = 'QueryGridPowerStopList';//查询网格停电事件
// var REQ_WEB_SER_CXTDSJGLSB = 'QueryGridPowerStopEquip';//查询停电事件关联设备
// var REQ_WEB_SER_CXTDYHXX = 'QueryBlackOutConsumer';//查询停电用户信息
// var REQ_WEB_SER_CXTDHZXX = 'QueryGridPowerStopStatistics';//查询停电汇总信息
// var REQ_WEB_SER_CXTFDGDXX = 'QueryGridOnOffPowefList';//查询停复电工单
// var REQ_WEB_SER_CXWGXX = 'QueryGridInfo';//查询网格信息
// var REQ_WEB_SER_CXWGMXXX = 'QueryGridInfoDetail';//查询网格明细信息
// var REQ_WEB_SER_BGWGSBXX = 'UploadGriEquipdInfo';//变更网格设备信息
// var REQ_WEB_SER_BGWGXX = 'UploadGridInfo';//变更网格信息
// var REQ_WEB_SER_CXWGTSKHMC = 'QueryGridCustomerComplainInfo';//查询网格投诉客户名册
// var REQ_WEB_SER_CXWGXSYC = 'QueryGridLineLossTrouble';//网格线损异常查询
// var REQ_WEB_SER_CXXSGZSL = 'QueryXsGzclsl';//查询线损异常和故障设备工单数量
// var REQ_WEB_SER_CXRYBS = 'QueryPersonnelIdentification';//查询网格经理下的人员标识
// var REQ_WEB_SER_CXXLTQ = 'QueryXlTqxx';//查询线路台区信息
// var REQ_WEB_SER_CXWGXLTQXSL = 'QueryGridLineLossRate';//查询网格线路台区线损率
// var REQ_WEB_SER_CXLSQFYHXX = 'DownloadHistoryQfUserInfo';//查询历史欠费用户信息
// var REQ_WEB_SER_CXDFHSYCFFMD = 'QueryElectricChargeEnomalyList';//查询网格电费核算异常分发名单
// var REQ_WEB_SER_CXJTDLYJKHMD = 'JtElectricWarning';//查询网格阶梯电量预警客户名单
// var REQ_WEB_SER_WGRCYWJK = 'GridDailyBusinessMonitoring';//网格日常业务监控
// var REQ_WEB_SER_CXXSYCYYFX = 'QueryLineLossEnomalAnalyze';//查询线损异常原因分析
// var REQ_WEB_SER_SCXSYCYYFX = 'UploadLineLossEnomalAnalyze';//上传线损异常原因分析
// var REQ_WEB_SER_CXDABGDLTBYHMD = 'QueryDABGDLTBMD';//查询线路台区档案变更与电量突变50%的用户名单
// var REQ_WEB_SER_CXWGWTQD = 'DownloadGridUserProblemListInfo';//查询网格问题清单
// var REQ_WEB_SER_CXYDKFSBKH = 'QueryYdkfsbkh';//查询银电联网扣费失败客户
// var REQ_WEB_SER_CXKHJLSQXX = 'QueryKHJLSQXX';//查询客户经理下诉求信息
// var REQ_WEB_SER_UPDATEKHSQXX = 'UpdateKHSQXX';//客户诉求办理、取消、作废
// var REQ_WEB_SER_CXYGYJCF = 'QueryYgUserInfo';//查询预购预警催费
// var REQ_WEB_SER_CXYJZXX = 'QueryJshYjInfo';//查询预警值信息
// var REQ_WEB_SER_GXJSHYJYZXX = 'UpdateJshYjYzInfo';//更新结算户预警阈值信息
// var REQ_WEB_SER_CXGDJK = 'QueryAgentListMonitor';//查询工单监控列表
// var REQ_WEB_SER_CXYWBQXL = 'QueryGridInfoByBs';//查询业务标签下拉树
// var REQ_WEB_SER_CXQFYH = 'QueryGridArrearsUsers';//查询欠费用户
// var REQ_WEB_SER_ZJCSCS = 'ArrearsUrgePayment';//添加一级催收
// var REQ_WEB_SER_CSSYYHQFZS = 'QueryGridUserNumSituation';//查询首页用户总数和欠费总数
// var REQ_WEB_SER_XASQGD = 'QueryCustomerDemandSheetList';// 下载诉求工作单
// var REQ_WEB_SER_XZWGJTZTQK = 'QueryGridStaticSituation';// 查询网格静态总体情况
// var REQ_WEB_SER_CXYKCSGD = 'QueryEnquiryTimeSheetList';//  查询业扩超时工单
// var REQ_WEB_SER_CXQXGDXX = 'QueryGridQXGZDXX';//  查询网格内抢修工单
// var REQ_WEB_SER_CXYHDGXX = 'QueryUserDgxx';//  查询用户电工信息
// var REQ_WEB_SER_BCDGXX = 'SaveDgjbxx';//  保存或删除电工信息
// var REQ_WEB_SER_BCDGZZXX = 'SaveDgzzxx';//  保存或删除电工资质信息
// var REQ_WEB_SER_BCDGBLXWJL = 'SaveDgblxwxx';//  保存或删除电工不良行为记录信息
// var REQ_WEB_SER_CSJLCX = 'QueryPromptCollectionInfo';// 催收记录查询
// var REQ_WEB_SER_QFYHCX = 'DownloadGridUserArrearsInfo';// 欠费用户查询
// var REQ_WEB_SER_WYJYHCX = 'QueryWYJYH';// 违约金用户查询
// var REQ_WEB_SER_LDLCX = 'QueryZeroElec';//  查询一段时间内零点量用户
// var REQ_WEB_SER_CXWGJLCF = 'QueryWgjlYsyhc';//  查询网格经理下的用户催费
// var REQ_WEB_SER_CXYWBL = 'QueryGridManagerBusinessSituation';//  自动化抄表率、抢修到达现场及时率
// var REQ_WEB_SER_CXYHXQXX = 'QueryYHXQXX';//  查询用户需求信息
// var REQ_WEB_SER_CXYZDCSSJ = 'GetMaxCssj';//  查询最大超时时间
// var REQ_WEB_SER_CXYXLTZXX= 'QueryXljlsbtzxx';//  从接口获取计量设备台站信息
// var REQ_WEB_SER_BCGDXX= 'SaveGzsbxx';//  保存工单信息
// var REQ_WEB_SER_KCDXXCX= 'QuerySurveySheetInfo';//  勘查单信息查询
// var REQ_WEB_SER_GZDGP= 'Gzdgp';//  工作单改派
// var REQ_WEB_SER_GXQXSJ= 'UploadQxsj';//  更新抢修工单中到达现场时间和恢复供电时间
// var REQ_WEB_SER_CCGCCL= 'DealProcedure';//  存储过程处理
// var REQ_WEB_SER_GXWGYH = 'QueryGridCustomerInfo';//查询网格用户信息
// var REQ_WEB_SER_CXWGDAWHXX = 'QueryWgdaxx';//查询网格档案维护信息
// var REQ_WEB_SER_CXWGDASBXX = 'QueryGridDeviceInformation';//查询网格档案维网格设备信息
// var REQ_WEB_SER_CXYHFYXX = 'QueryUserSealRunningInformation';//查询用户封印信息
// var REQ_WEB_SER_CXMFDZLK= 'QueryFreeElectricityDatabase';//  查询免费电资料库
// var REQ_WEB_SER_MFDZLKGL= 'MaintainFreeElectricityDatabase';//  免费电资料库管理
// var REQ_WEB_SER_MFDYHSQ= 'ApproveFreeElectricityUser';//  免费电用户申请
// var REQ_WEB_SER_CXYXSBZB= 'QueryRunningEquipmentInformation';//  查询运行设备坐标
// var REQ_WEB_SER_BCYXSBZB= 'UploadRunningEquipmentCoordinate';//  保存运行设备坐标
// var REQ_WEB_SER_CXSJHBDCS= 'QuerySjhbdcs';//  查询手机号绑定次数和是否空号，停机

var REQ_WEB_SER_CXGDS = 'interface1';//首页查询工单接口
var REQ_WEB_SER_CXKGGZD = 'interface2';//查询客服诉求工作单
var REQ_WEB_SER_CXTQYHSL = 'interface3';//台区用户数量查询
var REQ_WEB_SER_FSTQDX = 'interface4';//发送台区短信
var REQ_WEB_SER_CXWGTDSJ = 'interface5';//查询网格停电事件
var REQ_WEB_SER_CXTDSJGLSB = 'interface6';//查询停电事件关联设备
var REQ_WEB_SER_CXTDYHXX = 'interface7';//查询停电用户信息
var REQ_WEB_SER_CXTDHZXX = 'interface8';//查询停电汇总信息
var REQ_WEB_SER_CXTFDGDXX = 'interface9';//查询停复电工单
var REQ_WEB_SER_CXWGXX = 'interface10';//查询网格信息
var REQ_WEB_SER_CXWGMXXX = 'interface11';//查询网格明细信息
var REQ_WEB_SER_BGWGSBXX = 'interface12';//变更网格设备信息
var REQ_WEB_SER_BGWGXX = 'interface13';//变更网格信息
var REQ_WEB_SER_CXWGTSKHMC = 'interface14';//查询网格投诉客户名册
var REQ_WEB_SER_CXWGXSYC = 'interface15';//网格线损异常查询
var REQ_WEB_SER_CXXSGZSL = 'interface16';//查询线损异常和故障设备工单数量
var REQ_WEB_SER_CXRYBS = 'interface17';//查询网格经理下的人员标识
var REQ_WEB_SER_CXXLTQ = 'interface18';//查询线路台区信息
var REQ_WEB_SER_CXWGXLTQXSL = 'interface19';//查询网格线路台区线损率
var REQ_WEB_SER_CXLSQFYHXX = 'interface20';//查询历史欠费用户信息
var REQ_WEB_SER_CXDFHSYCFFMD = 'interface21';//查询网格电费核算异常分发名单
var REQ_WEB_SER_CXJTDLYJKHMD = 'interface22';//查询网格阶梯电量预警客户名单
var REQ_WEB_SER_WGRCYWJK = 'interface23';//网格日常业务监控
var REQ_WEB_SER_CXXSYCYYFX = 'interface24';//查询线损异常原因分析
var REQ_WEB_SER_SCXSYCYYFX = 'interface25';//上传线损异常原因分析
var REQ_WEB_SER_CXDABGDLTBYHMD = 'interface26';//查询线路台区档案变更与电量突变50%的用户名单
var REQ_WEB_SER_CXWGWTQD = 'interface27';//查询网格问题清单
var REQ_WEB_SER_CXYDKFSBKH = 'interface28';//查询银电联网扣费失败客户
var REQ_WEB_SER_CXKHJLSQXX = 'interface29';//查询客户经理下诉求信息
var REQ_WEB_SER_UPDATEKHSQXX = 'interface30';//客户诉求办理、取消、作废
var REQ_WEB_SER_CXYGYJCF = 'interface31';//查询预购预警催费
var REQ_WEB_SER_CXYJZXX = 'interface32';//查询预警值信息
var REQ_WEB_SER_GXJSHYJYZXX = 'interface33';//更新结算户预警阈值信息
var REQ_WEB_SER_CXGDJK = 'interface34';//查询工单监控列表
var REQ_WEB_SER_CXYWBQXL = 'interface35';//查询业务标签下拉树
var REQ_WEB_SER_CXQFYH = 'interface36';//查询欠费用户
var REQ_WEB_SER_ZJCSCS = 'interface37';//添加一级催收
var REQ_WEB_SER_CSSYYHQFZS = 'interface38';//查询首页用户总数和欠费总数
var REQ_WEB_SER_XASQGD = 'interface39';// 下载诉求工作单
var REQ_WEB_SER_XZWGJTZTQK = 'interface40';// 查询网格静态总体情况
var REQ_WEB_SER_CXYKCSGD = 'interface41';//  查询业扩超时工单
var REQ_WEB_SER_CXQXGDXX = 'interface42';//  查询网格内抢修工单
var REQ_WEB_SER_CXYHDGXX = 'interface43';//  查询用户电工信息
var REQ_WEB_SER_BCDGXX = 'interface44';//  保存或删除电工信息
var REQ_WEB_SER_BCDGZZXX = 'interface45';//  保存或删除电工资质信息
var REQ_WEB_SER_BCDGBLXWJL = 'interface46';//  保存或删除电工不良行为记录信息
var REQ_WEB_SER_CSJLCX = 'interface47';// 催收记录查询
var REQ_WEB_SER_QFYHCX = 'interface48';// 欠费用户查询
var REQ_WEB_SER_WYJYHCX = 'interface49';// 违约金用户查询
var REQ_WEB_SER_LDLCX = 'interface50';//  查询一段时间内零点量用户
var REQ_WEB_SER_CXWGJLCF = 'interface51';//  查询网格经理下的用户催费
var REQ_WEB_SER_CXYWBL = 'interface52';//  自动化抄表率、抢修到达现场及时率
var REQ_WEB_SER_CXYHXQXX = 'interface53';//  查询用户需求信息
var REQ_WEB_SER_CXYZDCSSJ = 'interface54';//  查询最大超时时间
var REQ_WEB_SER_CXYXLTZXX = 'interface55';//  从接口获取计量设备台站信息
var REQ_WEB_SER_BCGDXX = 'interface56';//  保存工单信息
var REQ_WEB_SER_KCDXXCX = 'interface57';//  勘查单信息查询
var REQ_WEB_SER_GZDGP = 'interface59';//  工作单改派
var REQ_WEB_SER_GXQXSJ = 'interface60';//  更新抢修工单中到达现场时间和恢复供电时间
var REQ_WEB_SER_CCGCCL = 'interface61';//  存储过程处理
var REQ_WEB_SER_GXWGYH = 'interface62';//查询网格用户信息
var REQ_WEB_SER_CXWGDAWHXX = 'interface63';//查询网格档案维护信息
var REQ_WEB_SER_CXWGDASBXX = 'interface64';//查询网格档案维网格设备信息
var REQ_WEB_SER_CXYHFYXX = 'interface65';//查询用户封印信息
var REQ_WEB_SER_CXMFDZLK = 'interface66';//  查询免费电资料库
var REQ_WEB_SER_MFDZLKGL = 'interface67';//  免费电资料库管理
var REQ_WEB_SER_MFDYHSQ = 'interface68';//  免费电用户申请
var REQ_WEB_SER_CXYXSBZB = 'interface69';//  查询运行设备坐标
var REQ_WEB_SER_BCYXSBZB = 'interface70';//  保存运行设备坐标
var REQ_WEB_SER_CXSJHBDCS = 'interface71';//  查询手机号绑定次数和是否空号，停机

